module.exports = {
    INVALID_SCHEMA_TYPE: 'ERROR_INVALID_SCHEMA_TYPE',
    ERROR_ADD_MANY_NOT_SUPPORTED: 'ERROR_ADD_MANY_NOT_SUPPORTED',
    BQ_INSERT_ERROR: 'BQ_INSERT_ERROR',
    JOB_TIMEOUT: 'JOB_TIMEOUT'
};